### ISSUE TITLE
Wireframe views from brainstorming session

### ISSUE THREAD

**Issue by alam-shahul** [alam-shahul/threast.exe#9]

**Comment by anneouyang** [comment]
Anne: people, profile
Shahul: art,  signin

**Comment by alam-shahul** [comment]
/art wireframe
![THREAST EXE Art Wireframe](https://user-images.githubusercontent.com/22669932/79918718-9dbdb000-83f2-11ea-987f-9ef741738151.jpeg)

Possible features:
- Search
- Diorama vs Normie mode
- Pagination?
- Sort by date/title/author

**Comment by anneouyang** [comment]
Wireframe

/people
![wireframe-people](https://user-images.githubusercontent.com/25739691/80318914-4b99d780-87c2-11ea-92cf-963f4f713eb2.jpg)

/profile
![wireframe-profile](https://user-images.githubusercontent.com/25739691/80318917-4f2d5e80-87c2-11ea-9123-0b9d38b7cdb5.jpg)

**Comment by alam-shahul** [comment]
Note: we need to design a logo, pick a color scheme, and wireframe a Navbar!

**Comment by alam-shahul** [comment]
Updates: still need to design a log, but color scheme has inadvertently been set. Also, Navbar is basically done.
